services:
  opensearch:
    image: opensearchproject/opensearch:2.11.1
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 10s
      retries: 12
    networks:
      - backend
    volumes:
      - opensearch_data:/usr/share/opensearch/data

  postgres:
    image: postgres:16
    container_name: my_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mindstore
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mindstore"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: my_backend
    depends_on:
      postgres: 
          condition: service_healthy
      opensearch: 
          condition: service_healthy 
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mindstore
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8080"]
      interval: 10s
      timeout: 10s
      retries: 12


  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.11.0
    container_name: opensearch-dashboards
    ports:
      - "5601:5601"
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: "true"
    depends_on:
      - opensearch
    networks:
      - backend


  frontend:
    build: ./frontend
    container_name: my_frontend
    depends_on:
      backend: 
          condition: service_healthy 
    ports:
      - "4200:80"
    networks:
      - backend


  opensearch-init:
    image: curlimages/curl
    container_name: opensearch-init
    depends_on:
      opensearch:
        condition: service_healthy
    volumes:
      - ./docker/opensearch-init:/init
    command: >
      sh -c "
        until curl -s http://opensearch:9200; do
          sleep 1
        done
        cd /init && sh init.sh
      "
    networks:
      - backend

  # manifoldcf:
  #   image: apache/manifoldcf
  #   container_name: manifoldcf
  #   ports:
  #     - "8345:8345"   # UI port (MCF Crawler UI)
  #     - "8341:8341"   # API or Agent communication
  #   depends_on:
  #     opensearch:
  #       condition: service_healthy
  #   volumes:
  #     - ./my-cacerts:/opt/mcf/cacerts:ro
  #     - manifoldcf_data:/opt/mcf/mcf_home 
  #   environment:
  #   -  JAVA_OPTS=-Djavax.net.ssl.trustStore=/opt/mcf/cacerts -Djavax.net.ssl.trustStorePassword=changeit -Djavax.net.ssl.trustStoreType=JKS
  #   networks:
  #     - backend
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:8345/mcf-crawler-ui/"]
  #     interval: 15s
  #     timeout: 10s
  #     retries: 10
    


volumes:
  pgdata:
  opensearch_data:
 # manifoldcf_data: 

networks:
  backend:
